name: bebikame
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  video_player: ^2.9.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.5
  get_it: ^8.0.3
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  audioplayers: ^6.1.0
  photo_manager: ^3.6.3
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6+13
  envied: ^1.0.1
  flutter_launcher_icons: ^0.14.2
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.0
  go_router: ^14.6.3

  cupertino_icons: ^1.0.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_ios.png"
  image_path_android: "assets/icon/icon_android.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_android.png"
  min_sdk_android: 24

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  envied_generator:

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icon/icon_ios.png
    - assets/icon/icon_android.png
    - assets/images/animal/bg_animal.jpg
    - assets/images/animal/cat.png
    - assets/images/animal/chicken.png
    - assets/images/animal/dog.png
    - assets/images/animal/elephant.png
    - assets/images/animal/goat.png
    - assets/images/bubble/bg_bubble.jpg
    - assets/images/bubble/bubble.png
    - assets/images/fireworks/bg_fireworks.jpg
    - assets/images/fireworks/fireworks1/fireworks1-0.png
    - assets/images/fireworks/fireworks1/fireworks1-1.png
    - assets/images/fireworks/fireworks1/fireworks1-2.png
    - assets/images/fireworks/fireworks1/fireworks1-3.png
    - assets/images/fireworks/fireworks1/fireworks1-4.png
    - assets/images/fireworks/fireworks1/fireworks1-5.png
    - assets/images/fireworks/fireworks1/fireworks1-6.png
    - assets/images/fireworks/fireworks1/fireworks1-7.png
    - assets/images/fireworks/fireworks1/fireworks1-8.png
    - assets/images/fireworks/fireworks1/fireworks1-9.png
    - assets/images/fireworks/fireworks1/fireworks1-10.png
    - assets/images/fireworks/fireworks1/fireworks1-11.png
    - assets/images/fireworks/fireworks1/fireworks1-12.png
    - assets/images/fireworks/fireworks1/fireworks1-13.png
    - assets/images/fireworks/fireworks1/fireworks1-14.png
    - assets/images/fireworks/fireworks1/fireworks1-15.png
    - assets/images/fireworks/fireworks1/fireworks1-16.png
    - assets/images/fireworks/fireworks1/fireworks1-17.png
    - assets/images/fireworks/fireworks1/fireworks1-18.png
    - assets/images/fireworks/fireworks1/fireworks1-19.png
    - assets/images/fireworks/fireworks1/fireworks1-20.png
    - assets/images/fireworks/fireworks1/fireworks1-21.png
    - assets/images/fireworks/fireworks1/fireworks1-22.png
    - assets/images/fireworks/fireworks1/fireworks1-23.png
    - assets/images/fireworks/fireworks1/fireworks1-24.png
    - assets/images/fireworks/fireworks1/fireworks1-25.png
    - assets/images/fireworks/fireworks1/fireworks1-26.png
    - assets/images/fireworks/fireworks1/fireworks1-27.png
    - assets/images/fireworks/fireworks1/fireworks1-28.png
    - assets/images/fireworks/fireworks1/fireworks1-29.png
    - assets/images/fireworks/fireworks1/fireworks1-30.png
    - assets/images/fireworks/fireworks1/fireworks1-31.png
    - assets/images/fireworks/fireworks2/fireworks2-0.png
    - assets/images/fireworks/fireworks2/fireworks2-1.png
    - assets/images/fireworks/fireworks2/fireworks2-2.png
    - assets/images/fireworks/fireworks2/fireworks2-3.png
    - assets/images/fireworks/fireworks2/fireworks2-4.png
    - assets/images/fireworks/fireworks2/fireworks2-5.png
    - assets/images/fireworks/fireworks2/fireworks2-6.png
    - assets/images/fireworks/fireworks2/fireworks2-7.png
    - assets/images/fireworks/fireworks2/fireworks2-8.png
    - assets/images/fireworks/fireworks2/fireworks2-9.png
    - assets/images/fireworks/fireworks2/fireworks2-10.png
    - assets/images/fireworks/fireworks2/fireworks2-11.png
    - assets/images/fireworks/fireworks2/fireworks2-12.png
    - assets/images/fireworks/fireworks2/fireworks2-13.png
    - assets/images/fireworks/fireworks2/fireworks2-14.png
    - assets/images/fireworks/fireworks2/fireworks2-15.png
    - assets/images/fireworks/fireworks2/fireworks2-16.png
    - assets/images/fireworks/fireworks2/fireworks2-17.png
    - assets/images/fireworks/fireworks2/fireworks2-18.png
    - assets/images/fireworks/fireworks2/fireworks2-19.png
    - assets/images/fireworks/fireworks2/fireworks2-20.png
    - assets/images/fireworks/fireworks2/fireworks2-21.png
    - assets/images/fireworks/fireworks2/fireworks2-22.png
    - assets/images/fireworks/fireworks2/fireworks2-23.png
    - assets/images/fireworks/fireworks2/fireworks2-24.png
    - assets/images/fireworks/fireworks2/fireworks2-25.png
    - assets/images/fireworks/fireworks2/fireworks2-26.png
    - assets/images/fireworks/fireworks2/fireworks2-27.png
    - assets/images/fireworks/fireworks2/fireworks2-28.png
    - assets/images/fireworks/fireworks2/fireworks2-29.png
    - assets/images/fireworks/fireworks2/fireworks2-30.png
    - assets/images/fireworks/fireworks2/fireworks2-31.png
    - assets/images/fireworks/fireworks3/fireworks3-0.png
    - assets/images/fireworks/fireworks3/fireworks3-1.png
    - assets/images/fireworks/fireworks3/fireworks3-2.png
    - assets/images/fireworks/fireworks3/fireworks3-3.png
    - assets/images/fireworks/fireworks3/fireworks3-4.png
    - assets/images/fireworks/fireworks3/fireworks3-5.png
    - assets/images/fireworks/fireworks3/fireworks3-6.png
    - assets/images/fireworks/fireworks3/fireworks3-7.png
    - assets/images/fireworks/fireworks3/fireworks3-8.png
    - assets/images/fireworks/fireworks3/fireworks3-9.png
    - assets/images/fireworks/fireworks3/fireworks3-10.png
    - assets/images/fireworks/fireworks3/fireworks3-11.png
    - assets/images/fireworks/fireworks3/fireworks3-12.png
    - assets/images/fireworks/fireworks3/fireworks3-13.png
    - assets/images/fireworks/fireworks3/fireworks3-14.png
    - assets/images/fireworks/fireworks3/fireworks3-15.png
    - assets/images/fireworks/fireworks3/fireworks3-16.png
    - assets/images/fireworks/fireworks3/fireworks3-17.png
    - assets/images/fireworks/fireworks3/fireworks3-18.png
    - assets/images/fireworks/fireworks3/fireworks3-19.png
    - assets/images/fireworks/fireworks3/fireworks3-20.png
    - assets/images/fireworks/fireworks3/fireworks3-21.png
    - assets/images/fireworks/fireworks3/fireworks3-22.png
    - assets/images/fireworks/fireworks3/fireworks3-23.png
    - assets/images/fireworks/fireworks3/fireworks3-24.png
    - assets/images/fireworks/fireworks3/fireworks3-25.png
    - assets/images/fireworks/fireworks3/fireworks3-26.png
    - assets/images/fireworks/fireworks3/fireworks3-27.png
    - assets/images/fireworks/fireworks3/fireworks3-28.png
    - assets/images/fireworks/fireworks3/fireworks3-29.png
    - assets/images/fireworks/fireworks3/fireworks3-30.png
    - assets/images/fireworks/fireworks3/fireworks3-31.png
    - assets/images/music/bg_music.jpg
    - assets/images/music/acoustic.png
    - assets/images/music/guitar.png
    - assets/images/music/piano.png
    - assets/images/music/drum.png
    - assets/images/music/violin.png
    - assets/images/night/bg_night.jpg
    - assets/images/night/moon.png
    - assets/images/night/star_smile.png
    - assets/images/night/star.png
    - assets/images/vehicle/bg_vehicle.jpg
    - assets/images/vehicle/ambulance.png
    - assets/images/vehicle/bicycle.png
    - assets/images/vehicle/car.png
    - assets/images/vehicle/motorcycle.png
    - assets/images/vehicle/patrolcar.png

    - assets/sounds/bubble/bubble.mp3
    - assets/sounds/fireworks/fireworks.mp3
    - assets/sounds/night/moon.mp3
    - assets/sounds/night/star.mp3
    - assets/sounds/night/star_smile.mp3
    - assets/sounds/animal/cat.mp3
    - assets/sounds/animal/dog.mp3
    - assets/sounds/animal/chicken.mp3
    - assets/sounds/animal/elephant.mp3
    - assets/sounds/animal/goat.mp3
    - assets/sounds/music/acoustic.mp3
    - assets/sounds/music/guitar.mp3
    - assets/sounds/music/piano.mp3
    - assets/sounds/music/violin.mp3
    - assets/sounds/music/drum.mp3
    - assets/sounds/vehicle/car.mp3
    - assets/sounds/vehicle/ambulance.mp3
    - assets/sounds/vehicle/bicycle.mp3
    - assets/sounds/vehicle/motorcycle.mp3
    - assets/sounds/vehicle/patrolcar.mp3
    - assets/sounds/bgm.mp3
    - assets/sounds/button_tap.mp3

  fonts:
    - family: HachiMaruPop
      fonts:
        - asset: assets/fonts/HachiMaruPop-Regular.ttf


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/icon_ios.png
  android: true
  ios: true
  android_12:
    image: assets/icon/icon_android.png
    icon_background_color: "#FFFFFF"